# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake + NSIS on Windows V3

on: [workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DMULTI=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # --- Добавьте этот шаг ---
    - name: Install NSIS
      run: choco install nsis -y

    - name: Create NSIS installer
      uses: joncloud/makensis-action@v5.0
      with:
        arguments: "/V3"
        script-file: ${{github.workspace}}/install.nsi

    - name: Get installer
      uses: actions/upload-artifact@v4
      with:
        name: drumlabooh-installer.exe
        path: drumlabooh-installer.exe