# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake art VSTi/LV2 on Ubuntu 24/04

on: [workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: |
          sudo apt update
          sudo apt install -y git make g++ cmake pkg-config libasound2-dev libfreetype-dev libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libglu1-mesa-dev mesa-common-dev
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Archive artifacts VST3
      uses: actions/upload-artifact@v4
      with:
       name: drumlabooh.vst3
       path: ${{github.workspace}}/build/drumlabooh_artefacts/Release/VST3

    - name: Archive artifacts LV2
      uses: actions/upload-artifact@v4
      with:
       name: drumlabooh.lv2
       path: ${{github.workspace}}/build/drumlabooh_artefacts/Release/LV2
